#include "stm32l475vg_mpu.h"
#include "stm32l4xx_hal.h"
#include "memory_map.h"
#include "it.h"
#include "tee_common.h"
#include "tee_client_api.h"
#include "internal_core_api.h"
#include "scheduler.h"
#include <stdint.h>


// Declare the structure used to store the parameters passed by the client to the TA
// The structure is placed in the TA's own memory section of the binary
TEE_Param  __attribute__((section(".data_TA1 "))) ta_params_1[4] = {0};
TEE_Param  __attribute__((section(".data_TA2 "))) ta_params_2[4] = {0};


/**
 * @brief Function to call the Trusted Execution Environment (TEE) Core API from a Trusted Application (TA)
 */
uintptr_t call_TEE(Context *ctx, ComponentID caller, uint8_t svc_num) {

	uintptr_t ret_val = TEE_FAILED; // Declare a variable to store the return value

    // TODO: It could be spoofed in the following scenario:
    // - The SVC handler is called.
    // - An interrupt is triggered.
    // - The PC is stored on the CA writable stack and therefore modified to a TEE compatible instruction.
    // - The operation is executed even if it was generated by the CA:
    // TODO: it is not sufficient to use a global "status" variable as the SVC could be called by an interrupt while in the TA state.
    // TODO: check if the MPU is reconfigured in case of interrupt while a TA is running.


    if (svc_num < 5 || svc_num > 50) {
        ret_val = TEE_FAILED;
    } else if (caller != COMPONENT_TA1 && caller != COMPONENT_TA2) {
    	ERR_MSG("Unstrusted applications can not execute privileged TEE Core API directly, exiting");
        ret_val = TEE_FAILED;
    } else {
	    // Based on the SVC number, call the internal implementation of the TEE Core API
    	// Each case corresponds to a function of the TEE Core API that offers services to the TAs
    	switch (svc_num) {
    		case FUNCTION_MALLOC:
    			// Extract the parameters from the manual frame and pass them to the internal implementation of TEE Core API
    			// As the values were passed in the registers to the SVC Handler, they are stored in the manual frame
    			ret_val = internal_TEE_Malloc(ctx->manual_frame.r4, ctx->manual_frame.r5, caller);
    			break;
    		case FUNCTION_FREE:
    			internal_TEE_Free((void*)ctx->manual_frame.r4, caller);
    			break;
    		case FUNCTION_MEM_MOVE:
    			internal_TEE_MemMove((void*)ctx->manual_frame.r4, (void*)ctx->manual_frame.r5, ctx->manual_frame.r6, caller);
    			break;
    		case FUNCTION_MEM_FILL:
    			internal_TEE_MemFill((void*)ctx->manual_frame.r4, ctx->manual_frame.r5, ctx->manual_frame.r6, caller);
    			break;
    		case FUNCTION_BIG_INT_CONVERT_TO_S32:
    			ret_val = (void *) internal_TEE_BigIntConvertToS32((int32_t*)ctx->manual_frame.r4, (TEE_BigInt*)ctx->manual_frame.r5, caller);
    			break;
    		case FUNCTION_BIG_INT_CMP_S32:
    			ret_val = (void *)internal_TEE_BigIntCmpS32((TEE_BigInt*)ctx->manual_frame.r4, ctx->manual_frame.r5, caller);
    			break;
    		case FUNCTION_BIG_INT_MOD:
    			internal_TEE_BigIntMod((TEE_BigInt*)ctx->manual_frame.r4, (TEE_BigInt*)ctx->manual_frame.r5, (TEE_BigInt*)ctx->manual_frame.r6, caller);
    			break;
    		case FUNCTION_BIG_INT_DIV:
    			internal_TEE_BigIntDiv((TEE_BigInt*)ctx->manual_frame.r4, (TEE_BigInt*)ctx->manual_frame.r5, (TEE_BigInt*)ctx->manual_frame.r6, (TEE_BigInt*)ctx->manual_frame.r7, caller);
    			break;
    		case FUNCTION_BIG_INT_CONVERT_FROM_OCTET_STRING:
    			ret_val = (void *)internal_TEE_BigIntConvertFromOctetString((TEE_BigInt*)ctx->manual_frame.r4, (uint8_t*)ctx->manual_frame.r5, ctx->manual_frame.r6, ctx->manual_frame.r7, caller);
    			break;
    		case FUNCTION_BIG_INT_INIT:
    			internal_TEE_BigIntInit((TEE_BigInt*)ctx->manual_frame.r4, ctx->manual_frame.r5, caller);
    			break;
    		case FUNCTION_ALLOCATE_TRANSIENT_OBJECT:
    			ret_val = (void *)internal_TEE_AllocateTransientObject(ctx->manual_frame.r4, ctx->manual_frame.r5, (TEE_ObjectHandle *)ctx->manual_frame.r6, caller);
    			break;
    		case FUNCTION_POPULATE_TRANSIENT_OBJECT:
    			ret_val = (void *)internal_TEE_PopulateTransientObject((TEE_ObjectHandle)ctx->manual_frame.r4, (TEE_Attribute *)ctx->manual_frame.r5, ctx->manual_frame.r6, caller);
    			break;
    		case FUNCTION_INIT_REF_ATTRIBUTE:
    			internal_TEE_InitRefAttribute((TEE_Attribute *)ctx->manual_frame.r4, ctx->manual_frame.r5, (void *)ctx->manual_frame.r6, ctx->manual_frame.r7, caller);
    			break;
    		case FUNCTION_INIT_VALUE_ATTRIBUTE:
    			internal_TEE_InitValueAttribute((TEE_Attribute *)ctx->manual_frame.r4, ctx->manual_frame.r5, ctx->manual_frame.r6, ctx->manual_frame.r7, caller);
    			break;
    		case FUNCTION_GET_OBJECT_BUFFER_ATTRIBUTE:
    			ret_val = (void *)internal_TEE_GetObjectBufferAttribute((TEE_ObjectHandle)ctx->manual_frame.r4, ctx->manual_frame.r5, (void*)ctx->manual_frame.r6, (size_t *)ctx->manual_frame.r7, caller);
    			break;
    		case FUNCTION_GET_OBJECT_VALUE_ATTRIBUTE:
    			ret_val = (void *)internal_TEE_GetObjectValueAttribute((TEE_ObjectHandle)ctx->manual_frame.r4, ctx->manual_frame.r5, (uint32_t*)ctx->manual_frame.r6, (uint32_t*)ctx->manual_frame.r7, caller);
    			break;
    		case FUNCTION_FREE_TRANSIENT_OBJECT:
    			internal_TEE_FreeTransientObject((TEE_ObjectHandle)ctx->manual_frame.r4, caller);
    			break;
    		case FUNCTION_CLOSE_OBJECT:
    			internal_TEE_CloseObject((TEE_ObjectHandle)ctx->manual_frame.r4, caller);
    			break;
    		case FUNCTION_READ_OBJECT_DATA:
    			ret_val = (void *)internal_TEE_ReadObjectData((TEE_ObjectHandle)ctx->manual_frame.r4, (void*)ctx->manual_frame.r5, ctx->manual_frame.r6, (size_t*)ctx->manual_frame.r7, caller);
    			break;
    		case FUNCTION_WRITE_OBJECT_DATA:
    			ret_val = (void *)internal_TEE_WriteObjectData((TEE_ObjectHandle)ctx->manual_frame.r4, (void*)ctx->manual_frame.r5, ctx->manual_frame.r6, caller);
    			break;
    		case FUNCTION_CREATE_PERSISTENT_OBJECT:
    			ret_val = (void *)internal_TEE_CreatePersistentObject(caller, (void *) ctx->manual_frame.r5, ctx->manual_frame.r6, ctx->manual_frame.r7,(TEE_ObjectHandle) ctx->manual_frame.r8,(void *)  ctx->manual_frame.r9, ctx->manual_frame.r10, (TEE_ObjectHandle *)ctx->manual_frame.r7, caller);
    			break;
    		case FUNCTION_OPEN_PERSISTENT_OBJECT:
    			ret_val = (void *)internal_TEE_OpenPersistentObject(caller,(void *) ctx->manual_frame.r5, ctx->manual_frame.r6, ctx->manual_frame.r7, (TEE_ObjectHandle *)ctx->manual_frame.r8, caller);
    			break;
    		case FUNCTION_CLOSE_DELETE_PERSISTENT_OBJECT:
    			ret_val = (void *)internal_TEE_CloseAndDeletePersistentObject((TEE_ObjectHandle)ctx->manual_frame.r4, caller);
    			break;
    		case FUNCTION_ALLOCATE_OPERATION:
    			ret_val = (void *)internal_TEE_AllocateOperation((TEE_OperationHandle *)ctx->manual_frame.r4, ctx->manual_frame.r5, ctx->manual_frame.r6, ctx->manual_frame.r7, caller);
    			break;
    		case FUNCTION_FREE_OPERATION:
    			internal_TEE_FreeOperation((TEE_OperationHandle)ctx->manual_frame.r4, caller);
    			break;
    		case FUNCTION_SET_OPERATION_KEY:
    			ret_val = (void *)internal_TEE_SetOperationKey((TEE_OperationHandle)ctx->manual_frame.r4, (TEE_ObjectHandle)ctx->manual_frame.r5, caller);
    			break;
    		case FUNCTION_SET_OPERATION_KEY2:
    			// NOTE: This function is not implemented in the TEE Core API
    			//ret_val = internal_TEE_SetOperationKey2(ctx->manual_frame.r4, ctx->manual_frame.r5, ctx->manual_frame.r6);
    			break;
    		case FUNCTION_GENERATE_KEY:
    			ret_val = (void *)internal_TEE_GenerateKey((TEE_ObjectHandle)ctx->manual_frame.r4, ctx->manual_frame.r5, (TEE_Attribute *)ctx->manual_frame.r6, ctx->manual_frame.r7, caller);
    			break;
    		case FUNCTION_GENERATE_RANDOM:
    			internal_TEE_GenerateRandom((void *)ctx->manual_frame.r4, ctx->manual_frame.r5, caller);
    			break;
    		case FUNCTION_DERIVE_KEY:
    			// NOTE: This function is not implemented in the TEE Core API
    			//ret_val = internal_TEE_DeriveKey(ctx->manual_frame.r4, ctx->manual_frame.r5, ctx->manual_frame.r6, ctx->manual_frame.r7);
    			break;
    		case FUNCTION_CIPHER_INIT:
    			internal_TEE_CipherInit((TEE_OperationHandle)ctx->manual_frame.r4, (void *)ctx->manual_frame.r5, ctx->manual_frame.r6, caller);
    			break;
    		case FUNCTION_CIPHER_UPDATE:
    			ret_val = (void *)internal_TEE_CipherUpdate((TEE_OperationHandle)ctx->manual_frame.r4, (void *)ctx->manual_frame.r5, ctx->manual_frame.r6, (void *)ctx->manual_frame.r7,(size_t *) ctx->manual_frame.r8, caller);
    			break;
    		case FUNCTION_CIPHER_DO_FINAL:
    			ret_val = (void *)internal_TEE_CipherDoFinal((TEE_OperationHandle)ctx->manual_frame.r4], (void*)ctx->manual_frame.r5], ctx->manual_frame.r6], (void*)ctx->manual_frame.r7], (size_t *) ctx->manual_frame.r8], caller);
    			break;
    		case FUNCTION_MAC_INIT:
    			internal_TEE_MACInit((TEE_OperationHandle)ctx->manual_frame.r4, (void *) ctx->manual_frame.r5, ctx->manual_frame.r6, caller);
    			break;
    		case FUNCTION_MAC_UPDATE:
    			internal_TEE_MACUpdate((TEE_OperationHandle)ctx->manual_frame.r4,(void *)  ctx->manual_frame.r5, ctx->manual_frame.r6, caller);
    			break;
    		case FUNCTION_MAC_COMPUTE_FINAL:
    			ret_val = (void *)internal_TEE_MACComputeFinal((TEE_OperationHandle)ctx->manual_frame.r4, (void*)ctx->manual_frame.r5, ctx->manual_frame.r6, (void*)ctx->manual_frame.r7, (size_t *)ctx->manual_frame.r8, caller);
    			break;
    		case FUNCTION_DIGEST_UPDATE:
    			internal_TEE_DigestUpdate((TEE_OperationHandle)ctx->manual_frame.r4, (void*)ctx->manual_frame.r5, ctx->manual_frame.r6, caller);
    			break;
    		case FUNCTION_DIGEST_DO_FINAL:
    			ret_val = (void *)internal_TEE_DigestDoFinal((TEE_OperationHandle)ctx->manual_frame.r4, (void*)ctx->manual_frame.r5, ctx->manual_frame.r6, (void*)ctx->manual_frame.r7, (size_t *)ctx->manual_frame.r8, caller);
    			break;
    		case FUNCTION_DIGEST_EXTRACT:
    			ret_val = (void *)internal_TEE_DigestExtract((TEE_OperationHandle)ctx->manual_frame.r4, (void *)ctx->manual_frame.r5, (size_t *)ctx->manual_frame.r6, caller);
    			break;
    		case FUNCTION_ASYMMETRIC_SIGN_DIGEST:
    			ret_val = (void *)internal_TEE_AsymmetricSignDigest((TEE_OperationHandle)ctx->manual_frame.r4,(TEE_Attribute *) ctx->manual_frame.r5, ctx->manual_frame.r6, (void*)ctx->manual_frame.r7, ctx->manual_frame.r8, (void*)ctx->manual_frame.r9,(size_t *) ctx->manual_frame.r10, caller);
    			break;
    		case FUNCTION_ASYMMETRIC_VERIFY_DIGEST:
    			ret_val = (void *)internal_TEE_AsymmetricVerifyDigest((TEE_OperationHandle)ctx->manual_frame.r4, (TEE_Attribute *)ctx->manual_frame.r5, ctx->manual_frame.r6,(void*) ctx->manual_frame.r7, ctx->manual_frame.r8, (void*)ctx->manual_frame.r9,  ctx->manual_frame.r10, caller);
    			break;
    		default:
    			break;
    	}
    }

    return ret_val;
}

/**
* MCU-Fortifier microvisor HardFault_Handler:
* - If the hard fault is caused by an unprivileged access to the PPB,
* 	the access is granted and executed under the control of MCU-Fortifier
* - In case of error during the recovery and simulation, the MCU is reset
*/
static void _microvisor_hardfault_handler(Context *ctx) {

    // Try to treat this hardfault as an exception return.
    if (return_catcher(ctx) == MATCHED) {
        return;
    }

    // Try to treat this hardfault as an unprivileged PPB access.
    if (Recover_PPB_Access(ctx) == MATCHED) {
        return;
    }

    soft_reset();
}

__attribute__((naked))
void Microvisor_HardFault_Handler(void) {
    // Delegate the call to scheduler_handle_context that must call _microvisor_hardfault_handler.
    SCHEDULER_HANDLE(_microvisor_hardfault_handler);
}


/*
* MCU-Fortifier microvisor SVC_Handler can be invoked for 4 reasons:
* - There is the need to simulate of a system instruction (the SVC was called due to the code instrumentation).
* 	In that case the instruction is simulated and the exception return is performed
* - The SVC was called by the client application to perform a Global Platform API call (SVC number is in the range 0-4)
* 	In that case the API call is performed and the exception return is performed
* - The SVC was called by a trusted application to perform a TEE Core API call (SVC number is in the range 5-50)
* 	In that case the API call is performed and the execution is returned to the trusted application
* - Otherwise the original SVC_Handler is performed
*
* When an SVC call is made, the following registers are pushed on the stack automatically:
* - r0: the return value of the SVC call
* - r1: the first parameter of the SVC call
* - r2: the second parameter of the SVC call
* - r3: the third parameter of the SVC call
* - r12:
* - lr: the link register, which contains the return address
* - pc: the program counter, which contains the address of the next instruction to execute
* - xPSR: the program status register, which contains the current state of the processor

* Notes on PARAMETER PASSING CONVENTION FOR SVC for both Client and Core API calls:
* - use registers from r4 to r11 to pass parameters to SVC 
* - save the current value of the registers used in a temporary variable before overwriting them
* - restore the value of the registers after the SVC call
* - use r4 to get the return value of the SVC invocation
*/
static void _microvisor_svc_handler(Context *ctx) {

    // TODO: the old code used the PC to recognize the TA and then checked the PSP. Is this a necessary check?
    if (check_registers(ctx) != MICROVISOR_OK) {
        // TODO: manage.
        while (1);
    }

    // Try to treat this hardfault as an exception return.
    if (Recover_System_Instruction(ctx) == MATCHED) {
        return;
    }

    // TODO: 		"ldr r3,[r0, #24]\n"	// load RetAddr
    //      		"ldrb r3,[r3, #-2]\n"	// load SVC number in r3
    uint8_t svc_num = recover_svc_num(ctx->auto_frame->PC);

    if (svc_num <= 4U) {
        // TODO: call TA api.
        // TODO: store BASEPRI.
        // TODO: nPRIV = 0? Do we really need privileges?
        // TODO: must change PSP, however this breaks the auto_frame that we are overwriting.

        // TODO: pass the process we want to switch to.
        // TODO: create ad hoc function.
        // TODO: check return.
        scheduler_schedule(ctx, COMPONENT_TA?, call_TA, return_client_api);

        // Only Thumb-mode flag.
        ctx->auto_frame->XPSR = 0x01000000;

        call_TA(ctx, svc_num);

        return;
    } else if (svc_num <= 50U) {
        ComponentID caller = get_caller(ctx);
        uintptr_t res = call_TEE(ctx, caller, svc_num);
        ctx->manual_frame->r4 = res;

        return;
    } else {
        _exception_catcher(ctx, svc_num);
        // TODO: exception catcher with original handler.
    }
}

__attribute__((naked))
void Microvisor_SVC_Handler() {
    // Delegate the call to scheduler_handle_context that must call _microvisor_svc_handler.
    SCHEDULER_HANDLE(_microvisor_svc_handler);
}

/**
 *  MCU-Fortifier microvisor MemManage_Handler:
 *  Detect if the fault is caused by an MPU violation and execute the MPU violation handler
 */
void _microvisor_memmanage_handler(Context *ctx) {
	ERR_MSG("MPU violation detected");
    MPU_Violation_Handler(ctx);
}

__attribute__((naked))
void Microvisor_MemManage_Handler() {
    // Delegate the call to scheduler_handle_context that must call _microvisor_memmanage_handler.
    SCHEDULER_HANDLE(_microvisor_memmanage_handler);
}
